### PR TITLE
Fix memory corruption in odd length MAC check

### PR DESCRIPTION
**Pull request by james-choncholas**
This change fixes a simple off by one error.

The out-of-bounds memory access happens at abitmp.h line 139 and 142 when an odd valued length is passed to check1() and check2() appears to have the same problem.

Although this change eliminates the out-of-bounds memory access, I'm not confident my fix is logically correct so please review carefully.

Thank you for sharing EMP-toolkit with the world!

I've included the [circuit file](https://github.com/emp-toolkit/emp-agmpc/files/5081236/circuit.txt)  which exhibited this issue and tested using CMAKE_BUILD_TYPE=Debug for debug symbols and USE_RANDOM_DEVICE=ON so valgrind wouldn't complain about the x86 intrinsics.

### CODE REVIEW

**Comment by wangxiao1254** [comment]
Thanks! Can you create a pull request with a test case using the circuit file you provided? I'm not sure that the modification here is secure but I will fix it offline (and test it against the example).

**Comment by james-choncholas** [comment]
As requested, I've added a test case with a build target called pr10_test. To see it in action, build with:
```
rm CMakeCache.txt
cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_RANDOM_DEVICE=ON .
make
```

From the top level directory of the repo, run 
```
./debug ./bin/pr10_test
```

Now, you can comment out my changes (```length -= length%2;``` on lines 102 and 200,) rebuild, and see valgrind complain about "Invalid write of size 1" and "Invalid read of size 1"

Now that I'm looking a little closer, it appears some other circuits in the repo, like sha256.txt, also exhibit this behavior where an odd valued length is passed into check1() and check2() and the code runs off the end of the "tb" array.

Again, my fix is pretty rudimentary and likely not logically correct

**Comment by james-choncholas** [comment]
Please ignore the PR closed/re-opened, it was an accident. I ran the wrong git command.

**Comment by wangxiao1254** [comment]
OK :) It will be fixed soon after I finished up the updates to ag2pc.

**Comment by weikengchen** [comment]
I encountered a similar issue in some of my programs. It seems the reason, as James said, is simply off-by-one:
```
		for(int i = 0; i < length; i+=chk) {
			tb[i/chk][1] = data[i];
			tb[i/chk][2] = data[i+1];
			tb[i/chk][3] = data[i] != data[i+1];
		}
```

```
				for(int i = SIZE*tt; i < SIZE*(tt+1) and i < length; i+=chk) {
				  tMAC[(i-start)/chk][1] = MAC[k][i];
				  tMAC[(i-start)/chk][2] = MAC[k][i+1];
				  tMAC[(i-start)/chk][3] = MAC[k][i] ^ MAC[k][i+1];

				  tKEY[(i-start)/chk][1] = KEY[k][i];
				  tKEY[(i-start)/chk][2] = KEY[k][i+1];
				  tKEY[(i-start)/chk][3] = KEY[k][i] ^ KEY[k][i+1];
				  for(int j = 0; j < ssp; ++j) {
							 Ms[k][j] = Ms[k][j] ^ tMAC[(i-start)/chk][*tmpptr];
							 Ks[k][j] = Ks[k][j] ^ tKEY[(i-start)/chk][*tmpptr];
							 bs[k][j] = bs[k][j] != tb[i/chk][*tmpptr];
							 ++tmpptr;
					}
				}
```

maybe we just need to change `i < length` to `i < length - 1`?

**Comment by wangxiao1254** [comment]
Let me figure out exactly what I was trying to do where and then will fix the bug. E.g. why I have this chk😂

**Comment by wangxiao1254** [comment]
I think the current version fixed the issue, but I'm not able to reproduce the issue. If anyone can test the latest version, it would be great.

**Pull request closed without merging**
